module.exports = [
  {
    name: 'tierOne',
    label: 'Tier One',
    tier: 1,
    price: 500,
    description: 'Villa Lodging - Lodging Meals - Program',
    roomType: 'Single',
    bedType: '',
    numberOfBedsAvailable: 0,
  },
  {
    name: 'tierTwo',
    label: 'Tier Two',
    tier: 2,
    price: 350,
    description: 'Villa Lodging - Lodging Meals - Program',
    roomType: 'Shared',
    bedType: 'Queen / Double / Full',
    numberOfBedsAvailable: 3,
  },
  {
    name: 'tierThree',
    label: 'Tier Three',
    tier: 3,
    price: 300,
    description: 'Villa Lodging - Lodging Meals - Program',
    roomType: 'Shared',
    bedType: 'Twin Bed',
    numberOfBedsAvailable: 4,
  },
];
